use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_dir = PathBuf::from(&crate_dir).join("include");

    // Create include directory if it doesn't exist
    std::fs::create_dir_all(&output_dir).unwrap();

    // Configure cbindgen
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        namespace: Some("cdfa".to_string()),
        include_guard: Some("CDFA_H".to_string()),
        autogen_warning: Some(
            "/* This file is auto-generated by cbindgen. Do not edit manually. */".to_string(),
        ),
        includes: vec!["stdint.h".to_string(), "stdbool.h".to_string()],
        export: cbindgen::ExportConfig {
            include: vec!["cdfa_.*".to_string()],
            exclude: vec![],
            ..Default::default()
        },
        ..Default::default()
    };

    // Generate C header
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(output_dir.join("cdfa.h"));

    // Tell cargo to rerun this build script if the source changes
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=build.rs");
}