//! Build script for qks-plugin
//!
//! Generates C header file using cbindgen for FFI integration

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Only generate header if FFI feature is enabled
    #[cfg(feature = "ffi")]
    {
        // Configure cbindgen
        let config = cbindgen::Config {
            language: cbindgen::Language::C,
            cpp_compat: true,
            include_guard: Some("QKS_PLUGIN_H".to_string()),
            autogen_warning: Some(
                "/* WARNING: This file is auto-generated by cbindgen. Do not modify manually. */".to_string()
            ),
            documentation: true,
            documentation_style: cbindgen::DocumentationStyle::C99,
            line_length: 100,
            tab_width: 4,
            ..Default::default()
        };

        // Generate C header
        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_config(config)
            .with_include_guard("QKS_PLUGIN_H")
            .with_language(cbindgen::Language::C)
            .with_namespace("qks")
            .generate()
            .expect("Unable to generate bindings")
            .write_to_file(out_dir.join("qks_plugin.h"));

        println!("cargo:rerun-if-changed=src/");
        println!("cargo:rerun-if-changed=Cargo.toml");

        // Copy header to include directory for easier access
        let include_dir = PathBuf::from(&crate_dir).join("include");
        if !include_dir.exists() {
            std::fs::create_dir_all(&include_dir).unwrap();
        }

        let header_path = include_dir.join("qks_plugin.h");
        std::fs::copy(out_dir.join("qks_plugin.h"), &header_path)
            .expect("Failed to copy header file");

        println!("Generated C header at: {}", header_path.display());
    }
}
